const postTypes = {
  GET_POST: 'GET_POST',
  GET_POST_SUCCEDED: 'GET_POST_SUCCEDED',
  GET_POST_FAILED: 'GET_POST_FAILED',
  GET_POSTS: 'GET_POSTS',
  GET_POSTS_SUCCEDED: 'GET_POSTS_SUCCEDED',
  GET_POSTS_FAILED: 'GET_POSTS_FAILED',
};

export default postTypes;
