const postTypes = {
  GET_USERS: 'GET_USERS',
  GET_USERS_SUCCEDED: 'GET_USERS_SUCCEDED',
  GET_USERS_FAILED: 'GET_USERS_FAILED',
  GET_USER: 'GET_USER',
  GET_USER_SUCCEDED: 'GET_USER_SUCCEDED',
  GET_USER_FAILED: 'GET_USER_FAILED',
};

export default postTypes;
