const commentTypes = {
  GET_COMMENT: 'GET_COMMENT',
  GET_COMMENT_SUCCEDED: 'GET_COMMENT_SUCCEDED',
  GET_COMMENT_FAILED: 'GET_COMMENT_FAILED',
  GET_COMMENTS: 'GET_COMMENTS',
  GET_COMMENTS_SUCCEDED: 'GET_COMMENTS_SUCCEDED',
  GET_COMMENTS_FAILED: 'GET_COMMENTS_FAILED',
  GET_COMMENTS_BY_POST_ID: 'GET_COMMENTS_BY_POST_ID',
  GET_COMMENTS_BY_POST_ID_SUCCEDED: 'GET_COMMENTS_BY_POST_ID_SUCCEDED',
  GET_COMMENTS_BY_POST_ID_FAILED: 'GET_COMMENTS_BY_POST_ID_FAILED',
  ADD_COMMENT: 'ADD_COMMENT',
  ADD_COMMENT_SUCCEDED: 'ADD_COMMENT_SUCCEDED',
  ADD_COMMENT_FAILED: 'ADD_COMMENT_FAILED',
  ADD_TAGS: 'ADD_TAGS',
  ADD_TAGS_SUCCEDED: 'ADD_TAGS_SUCCEDED',
  ADD_TAGS_FAILED: 'ADD_TAGS_FAILED',
};

export default commentTypes;
